FROM ubuntu                                                                   
MAINTAINER Andres Diaz
RUN apt-get update -y && apt-get upgrade -y 
RUN apt-get install vsftpd -y
RUN sed -i 's/#write_enable=YES/write_enable=YES/g' /etc/vsftpd.conf
RUN sed -i 's/#anonymous_enable=YES/anonymous_enable=YES/g' /etc/vsftpd.conf
RUN sed -i 's/#ftpd_banner=Welcome to blah FTP service./ftpd_banner=Computacion en la Nube 2020./g' /etc/vsftpd.conf
RUN echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
RUN useradd -d /home/adiaz adiaz
RUN mkdir /home/adiaz
RUN chmod -R 777 /home/adiaz
RUN echo "adiaz:12345"|chpasswd
RUN /etc/init.d/vsftpd restart
EXPOSE 20 21
CMD ["/usr/sbin/vsftpd"]

